[package]
name = "idris_call"
version = "0.1.0"
authors = ["wires <jelle@defekt.nl>"]

[lib]
name = "idris_call"
crate-type = ["dylib", "rlib"]

[dependencies]
libc = { version = "0.2", default-features = false }
